### ISSUE TITLE
在Z100L上无法运行resnet50-v2.7

### ISSUE THREAD

**Issue by XzZZzX02** [wangzy0327/tvm-sycl-summary#1]
系统版本: Ubuntu-20.04
llvm: llvm-9
DPC++: openDPC++-llvm20
使用tvmc可以进行模型的编译, 但是在tvmc run时无法指定device为sycl, 有如下报错:
另外, 我注意到/runtime/sycl/sycl_module.cc里的`SYCLModuleNode::Init()`的函数里的`this->lib_compiler.load_from_file`并没有被正确的设置为1, 导致无法从生成的临时sycl文件中读取kernel
```
[SYCL] Load kernels source code from file(/root/workspace/sycl_workspace/tvm-sycl/tmp/sycl_54446_1.cc).
[SYCL] Compile kernels source code(/root/workspace/sycl_workspace/tvm-sycl/tmp/sycl_54446_1.cc) to share library.
In file included from /root/workspace/sycl_workspace/tvm-sycl/tmp/sycl_54446_1.cc:2:
/root/workspace/sycl_workspace/llvm/build/bin/../include/CL/sycl.hpp:14:2: warning: "CL/sycl.hpp
      is deprecated, use sycl/sycl.hpp" [-W#warnings]
   14 | #warning "CL/sycl.hpp is deprecated, use sycl/sycl.hpp"
      |  ^
1 warning generated.
In file included from /root/workspace/sycl_workspace/tvm-sycl/tmp/sycl_54446_1.cc:2:
/root/workspace/sycl_workspace/llvm/build/bin/../include/CL/sycl.hpp:14:2: warning: "CL/sycl.hpp
      is deprecated, use sycl/sycl.hpp" [-W#warnings]
   14 | #warning "CL/sycl.hpp is deprecated, use sycl/sycl.hpp"
      |  ^
1 warning generated.
2024-12-20 16:30:54.758 INFO load_module /tmp/tmpcphx1zqu/mod.so
Traceback (most recent call last):
  File "/root/workspace/miniconda3/envs/tvm/bin/tvmc", line 33, in <module>
    sys.exit(load_entry_point('tvm', 'console_scripts', 'tvmc')())
  File "/root/workspace/sycl_workspace/tvm-sycl/python/tvm/driver/tvmc/main.py", line 115, in main
    sys.exit(_main(sys.argv[1:]))
  File "/root/workspace/sycl_workspace/tvm-sycl/python/tvm/driver/tvmc/main.py", line 103, in _main
    return args.func(args)
  File "/root/workspace/sycl_workspace/tvm-sycl/python/tvm/driver/tvmc/runner.py", line 280, in drive_run
    result = run_module(
  File "/root/workspace/sycl_workspace/tvm-sycl/python/tvm/driver/tvmc/runner.py", line 691, in run_module
    module.run()
  File "/root/workspace/sycl_workspace/tvm-sycl/python/tvm/contrib/graph_executor.py", line 208, in run
    self._run()
  File "/root/workspace/sycl_workspace/tvm-sycl/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  5: TVMFuncCall
  4: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  3: tvm::runtime::LocalSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  2: _ZN3tvm7runtime13PackedFuncObj9ExtractorINS0_16PackedFuncSubObjIZNS0_13GraphExecutor11GetFunctionERKNSt7__cxx
  1: _ZNSt17_Function_handlerIFvvEZN3tvm7runtime13GraphExecutor11CreateTVMOpERKNS2_10TVMOpParamERKSt6vectorI8DLTensorSaIS8_EEE3$_2E9_M_invokeERKS
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::WrapPackedFunc(int (*)(TVMValue*, int*, int, TVMValue*, int*, void*), tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::$_0> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/root/workspace/sycl_workspace/tvm-sycl/src/runtime/library_module.cc", line 88
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------

  Check failed: ret == 0 (-1 vs. 0) : Assert fail: (36 == tir.tvm_struct_get(arg.p0, 0, 10)), Argument arg.p0.device_type has an unsatisfied constraint: (36 == tir.tvm_struct_get(arg.p0, 0, 10))
```

**Comment by wangzy0327** [comment]
您这里用的sycl版本是intel-llvm的v2022-12 版本么？Z100L的硬件架构记得是 gfx916吧？

**Comment by XzZZzX02** [comment]
并不是, 是最近intel/llvm的某一个commit版本, Z100L的硬件架构是gfx906, 我貌似已经解决了这个问题, 貌似是因为tvmc并没有接入相关的支持? 直接调用tvm和tvm.relay就可以正常对resnet50-v2.7进行编译和推理

**Comment by wangzy0327** [comment]
新版的intel/llvm 我没有尝试过，不太好直接回答
